# Generated by Django 3.2.25 on 2024-07-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_collections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collections',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='collections',
            name='description',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
